spring:
  datasource:
    url: jdbc:postgresql://author-db:5432/authordb
    username: authoruser
    password: authorpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: author-service

server:
  port: 8087

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: author-service  # Use the service name from docker-compose
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    org:
      springframework:
        security: DEBUG