spring:
  datasource:
    url: jdbc:postgresql://book-db:5432/bookdb
    username: bookuser
    password: bookpass
    driver-class-name: org.postgresql.Driver
  application:
    name: book-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 3000
        loggerLevel: full  # Optional: for debugging Feign requests

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: book-service  # Use the service name from docker-compose
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: 8082

logging:
  level:
    org:
      springframework:
        security: DEBUG